- name: Create k8s vms
  hosts: localhost
  vars:
    k8s_config:
      - host: ps0
        ip: 172.16.100.91
        vmid: 100
      - host: ps1
        ip: 172.16.100.92
        vmid: 102
      - host: ps2
        ip: 172.16.100.93
        vmid: 103
  tasks:
    - name: Create k8s host
      community.general.proxmox_kvm:
        api_user: "{{ lookup('env', 'PROXMOX_USER') }}"
        api_password: "{{ lookup('env', 'PROXMOX_PASS') }}"
        api_host: "{{ lookup('env', 'PROXMOX_HOST') }}"
        clone: "debian-base"
        vmid: "{{ item.vmid }}"
        name: "kubernetes-{{ item.host }}"
        node: "{{ item.host }}"
        boot: "d"
        timeout: 500
      with_items: " {{ vars.k8s_config }}"

    - name: Config vm
      community.general.proxmox_kvm:
        api_user: "{{ lookup('env', 'PROXMOX_USER') }}"
        api_password: "{{ lookup('env', 'PROXMOX_PASS') }}"
        api_host: "{{ lookup('env', 'PROXMOX_HOST') }}"
        node: "{{ item.host }}"
        name: "kubernetes-{{ item.host }}"
        ciuser: root
        bootdisk: "scsi0"
        cores: 4
        sshkeys: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"
        agent: yes
        ipconfig:
          ipconfig0: 'ip={{ item.ip }}/24,gw=172.16.100.1'
        update: yes
      with_items: " {{ vars.k8s_config }}"

    - name: Ensure that all vms are started
      community.general.proxmox_kvm:
        api_user: "{{ lookup('env', 'PROXMOX_USER') }}"
        api_password: "{{ lookup('env', 'PROXMOX_PASS') }}"
        api_host: "{{ lookup('env', 'PROXMOX_HOST') }}"
        node: "{{ item.host }}"
        name: "kubernetes-{{ item.host }}"
        state: started
      with_items: " {{ vars.k8s_config }}"
    - name: Wait for vms to start
      wait_for:
        host: "{{ item.ip }}"
        port: 22
      with_items: " {{ vars.k8s_config }}"

- name: Copy ssh key for maintanance
  hosts: all
  tasks:
    - name: Ensure that ssh copy utility is installed
      apt:
        pkg:
          - ssh-import-id

    - name: Import ssh key
      shell: ssh-import-id gh:Hnatekmar

- import_playbook: ./ansible/kubernetes.yml
