- name: Install gitlab
  hosts: all
  remote_user: root
  tasks:
    - name: Install prerequisites
      apt:
        pkg:
          - debian-keyring
          - debian-archive-keyring
          - apt-transport-https
          - curl
    - name: Add caddy repository
      shell: "{{ item }}"
      with_items:
        - curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | tee /etc/apt/trusted.gpg.d/caddy-stable.asc
        - curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | tee /etc/apt/sources.list.d/caddy-stable.list
        - apt-get update
        - apt install caddy

    - name: Copy caddyfile
      copy:
        src: Caddyfile
        dest: /etc/caddy/Caddyfile
        force: yes

    - name: Reboot proxy
      shell: caddy reload --config /etc/caddy/Caddyfile
