- name: Install gitlab
  hosts: all
  remote_user: root
  tasks:
    - name: Install prerequisites
      apt:
        pkg:
          - nginx

    - name: Copy config
      copy:
        src: nginx.conf
        dest: /etc/nginx/nginx.conf
        force: yes


    - name: Decode certs
      shell: sops -d -i certs.tar.gz
      delegate_to: 127.0.0.1

    - name: Copy certs to target
      copy:
        src: certs.tar.gz
        dest: /root/certs.tar.gz
        force: yes

    - name: Encrypt certs
      shell: sops -e -a age1kmekcggsc7yuger35jklhv7k74uf78wfgv2cgj6hren4vjskcumq5xar4q -i certs.tar.gz
      delegate_to: 127.0.0.1

    - name: Unzip certs
      unarchive:
        src: /root/certs.tar.gz
        dest: /root/
        remote_src: yes

    - name: Reload nginx
      shell: systemctl restart nginx