---
- name: Prepare kubernetes
  remote_user: root
  hosts:
    - kubernetes_master
    - kubernetes_node
  tasks:
    - name: Install prerequisites
      apt:
        pkg:
          - curl
          - nfs-common

- name: Install k3s and join nodes
  hosts: kubernetes_master
  remote_user: root
  tasks:
    - name: Install k3s on all nodes
      delegate_to: 127.0.0.1
      command: k3sup install --host "{{ item }}" --ssh-key ~/.ssh/id_ed25519 --user root --local-path ~/.kube/kubeconfig
      with_items:
        - 172.16.100.91
#        - 172.16.100.92
#        - 172.16.100.93
    - name: Join all nodes
      delegate_to: 127.0.0.1
      command: k3sup join --ip "{{ item }}" --server-ip 172.16.100.91 --ssh-key ~/.ssh/id_ed25519 --user root
      with_items:
        - 172.16.100.92
        - 172.16.100.93

